/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define osprgm ((rpc_uint)0x20000001)
#define osprgm_vs ((rpc_uint)1)

#ifdef __cplusplus
#define osrpc ((rpc_uint)1)
extern "C" int * osrpc_1(char **, CLIENT *);
extern "C" int * osrpc_1_svc(char **, struct svc_req *);

#elif __STDC__
#define osrpc ((rpc_uint)1)
extern  int * osrpc_1(char **, CLIENT *);
extern  int * osrpc_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define osrpc ((rpc_uint)1)
extern  int * osrpc_1();
extern  int * osrpc_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_H_RPCGEN */
